# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ggpo\gui\ui\ggpowindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(810, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("assets/icon-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uiSplitter = QtGui.QSplitter(self.centralwidget)
        self.uiSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.uiSplitter.setObjectName(_fromUtf8("uiSplitter"))
        self.uiChannelsTree = QtGui.QTreeWidget(self.uiSplitter)
        self.uiChannelsTree.setObjectName(_fromUtf8("uiChannelsTree"))
        self.uiChannelsTree.headerItem().setText(0, _fromUtf8("#"))
        self.uiChannelsTree.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiChannelsTree.headerItem().setText(1, _fromUtf8("Game"))
        self.uiChannelsTree.headerItem().setTextAlignment(1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.layoutWidget = QtGui.QWidget(self.uiSplitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiTmPanel = QtGui.QFrame(self.layoutWidget)
        self.uiTmPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.uiTmPanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.uiTmPanel.setBaseSize(QtCore.QSize(0, 0))
        self.uiTmPanel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiTmPanel.setFrameShadow(QtGui.QFrame.Raised)
        self.uiTmPanel.setObjectName(_fromUtf8("uiTmPanel"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.uiTmPanel)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.uiLblTmTitle = QtGui.QLabel(self.uiTmPanel)
        self.uiLblTmTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.uiLblTmTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.uiLblTmTitle.setFont(font)
        self.uiLblTmTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.uiLblTmTitle.setObjectName(_fromUtf8("uiLblTmTitle"))
        self.verticalLayout_13.addWidget(self.uiLblTmTitle)
        self.uiTmStacked = QtGui.QStackedWidget(self.uiTmPanel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTmStacked.sizePolicy().hasHeightForWidth())
        self.uiTmStacked.setSizePolicy(sizePolicy)
        self.uiTmStacked.setMinimumSize(QtCore.QSize(0, 120))
        self.uiTmStacked.setObjectName(_fromUtf8("uiTmStacked"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.uiTmRegStatus = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uiTmRegStatus.setFont(font)
        self.uiTmRegStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmRegStatus.setObjectName(_fromUtf8("uiTmRegStatus"))
        self.verticalLayout_5.addWidget(self.uiTmRegStatus)
        self.uiTmRegTimer = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uiTmRegTimer.setFont(font)
        self.uiTmRegTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmRegTimer.setObjectName(_fromUtf8("uiTmRegTimer"))
        self.verticalLayout_5.addWidget(self.uiTmRegTimer)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.uiTmRegisterButton = QtGui.QPushButton(self.page)
        self.uiTmRegisterButton.setMinimumSize(QtCore.QSize(200, 0))
        self.uiTmRegisterButton.setObjectName(_fromUtf8("uiTmRegisterButton"))
        self.horizontalLayout_5.addWidget(self.uiTmRegisterButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.uiTmStacked.addWidget(self.page)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.page_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.uiTmNextOpponent = QtGui.QLabel(self.page_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uiTmNextOpponent.setFont(font)
        self.uiTmNextOpponent.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmNextOpponent.setWordWrap(True)
        self.uiTmNextOpponent.setObjectName(_fromUtf8("uiTmNextOpponent"))
        self.verticalLayout_4.addWidget(self.uiTmNextOpponent)
        self.uiTmStacked.addWidget(self.page_9)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.uiTmLblRound = QtGui.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uiTmLblRound.setFont(font)
        self.uiTmLblRound.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmLblRound.setObjectName(_fromUtf8("uiTmLblRound"))
        self.verticalLayout_10.addWidget(self.uiTmLblRound)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.uiTmLblMe = QtGui.QLabel(self.page_4)
        self.uiTmLblMe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiTmLblMe.setObjectName(_fromUtf8("uiTmLblMe"))
        self.horizontalLayout_11.addWidget(self.uiTmLblMe)
        self.uiTmLblReadyMe = QtGui.QLabel(self.page_4)
        self.uiTmLblReadyMe.setObjectName(_fromUtf8("uiTmLblReadyMe"))
        self.horizontalLayout_11.addWidget(self.uiTmLblReadyMe)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.uiTmLblOpp = QtGui.QLabel(self.page_4)
        self.uiTmLblOpp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiTmLblOpp.setObjectName(_fromUtf8("uiTmLblOpp"))
        self.horizontalLayout_12.addWidget(self.uiTmLblOpp)
        self.uiTmLblReadyOpp = QtGui.QLabel(self.page_4)
        self.uiTmLblReadyOpp.setObjectName(_fromUtf8("uiTmLblReadyOpp"))
        self.horizontalLayout_12.addWidget(self.uiTmLblReadyOpp)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.uiTmBtnReady = QtGui.QPushButton(self.page_4)
        self.uiTmBtnReady.setObjectName(_fromUtf8("uiTmBtnReady"))
        self.horizontalLayout_13.addWidget(self.uiTmBtnReady)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.uiTmStacked.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.uiTmLblRound2 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.uiTmLblRound2.setFont(font)
        self.uiTmLblRound2.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmLblRound2.setObjectName(_fromUtf8("uiTmLblRound2"))
        self.verticalLayout_14.addWidget(self.uiTmLblRound2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_2 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_14.addWidget(self.label_2)
        self.uiTmReportMe = QtGui.QLineEdit(self.page_5)
        self.uiTmReportMe.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmReportMe.setFont(font)
        self.uiTmReportMe.setObjectName(_fromUtf8("uiTmReportMe"))
        self.horizontalLayout_14.addWidget(self.uiTmReportMe)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.uiTmReportOpp = QtGui.QLineEdit(self.page_5)
        self.uiTmReportOpp.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmReportOpp.setFont(font)
        self.uiTmReportOpp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiTmReportOpp.setObjectName(_fromUtf8("uiTmReportOpp"))
        self.horizontalLayout_15.addWidget(self.uiTmReportOpp)
        self.label_8 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_15.addWidget(self.label_8)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.uiTmBtnSubmit = QtGui.QPushButton(self.page_5)
        self.uiTmBtnSubmit.setObjectName(_fromUtf8("uiTmBtnSubmit"))
        self.horizontalLayout_17.addWidget(self.uiTmBtnSubmit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.uiTmLblReportStatus = QtGui.QLabel(self.page_5)
        self.uiTmLblReportStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmLblReportStatus.setObjectName(_fromUtf8("uiTmLblReportStatus"))
        self.verticalLayout_14.addWidget(self.uiTmLblReportStatus)
        self.uiTmStacked.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.uiTmModMatches = QtGui.QListWidget(self.page_6)
        self.uiTmModMatches.setMaximumSize(QtCore.QSize(16777215, 100))
        self.uiTmModMatches.setObjectName(_fromUtf8("uiTmModMatches"))
        self.verticalLayout_8.addWidget(self.uiTmModMatches)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.uiTmModP1 = QtGui.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmModP1.setFont(font)
        self.uiTmModP1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiTmModP1.setObjectName(_fromUtf8("uiTmModP1"))
        self.horizontalLayout_19.addWidget(self.uiTmModP1)
        self.uiTmModScore1 = QtGui.QLineEdit(self.page_6)
        self.uiTmModScore1.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmModScore1.setFont(font)
        self.uiTmModScore1.setObjectName(_fromUtf8("uiTmModScore1"))
        self.horizontalLayout_19.addWidget(self.uiTmModScore1)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.uiTmModScore2 = QtGui.QLineEdit(self.page_6)
        self.uiTmModScore2.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmModScore2.setFont(font)
        self.uiTmModScore2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiTmModScore2.setObjectName(_fromUtf8("uiTmModScore2"))
        self.horizontalLayout_20.addWidget(self.uiTmModScore2)
        self.uiTmModP2 = QtGui.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uiTmModP2.setFont(font)
        self.uiTmModP2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uiTmModP2.setObjectName(_fromUtf8("uiTmModP2"))
        self.horizontalLayout_20.addWidget(self.uiTmModP2)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_18)
        self.uiTmModScoreSubmit = QtGui.QPushButton(self.page_6)
        self.uiTmModScoreSubmit.setObjectName(_fromUtf8("uiTmModScoreSubmit"))
        self.horizontalLayout_7.addWidget(self.uiTmModScoreSubmit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.uiTmModReports = QtGui.QLabel(self.page_6)
        self.uiTmModReports.setObjectName(_fromUtf8("uiTmModReports"))
        self.verticalLayout_8.addWidget(self.uiTmModReports)
        self.uiTmStacked.addWidget(self.page_6)
        self.verticalLayout_13.addWidget(self.uiTmStacked)
        self.uiTmBracketFrm = QtGui.QFrame(self.uiTmPanel)
        self.uiTmBracketFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.uiTmBracketFrm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.uiTmBracketFrm.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiTmBracketFrm.setFrameShadow(QtGui.QFrame.Raised)
        self.uiTmBracketFrm.setObjectName(_fromUtf8("uiTmBracketFrm"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.uiTmBracketFrm)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.uiTmBracketLink = QtGui.QLabel(self.uiTmBracketFrm)
        self.uiTmBracketLink.setAlignment(QtCore.Qt.AlignCenter)
        self.uiTmBracketLink.setOpenExternalLinks(True)
        self.uiTmBracketLink.setObjectName(_fromUtf8("uiTmBracketLink"))
        self.horizontalLayout_10.addWidget(self.uiTmBracketLink)
        self.uiTmBtnRules = QtGui.QPushButton(self.uiTmBracketFrm)
        self.uiTmBtnRules.setObjectName(_fromUtf8("uiTmBtnRules"))
        self.horizontalLayout_10.addWidget(self.uiTmBtnRules)
        self.uiTmBtnMod = QtGui.QPushButton(self.uiTmBracketFrm)
        self.uiTmBtnMod.setObjectName(_fromUtf8("uiTmBtnMod"))
        self.horizontalLayout_10.addWidget(self.uiTmBtnMod)
        self.verticalLayout_13.addWidget(self.uiTmBracketFrm)
        self.verticalLayout.addWidget(self.uiTmPanel)
        self.uiChatHistoryTxtB = QtGui.QTextBrowser(self.layoutWidget)
        self.uiChatHistoryTxtB.setAcceptDrops(False)
        self.uiChatHistoryTxtB.setReadOnly(True)
        self.uiChatHistoryTxtB.setOpenExternalLinks(False)
        self.uiChatHistoryTxtB.setOpenLinks(False)
        self.uiChatHistoryTxtB.setObjectName(_fromUtf8("uiChatHistoryTxtB"))
        self.verticalLayout.addWidget(self.uiChatHistoryTxtB)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uiChatInputEdit = CompletionLineEdit(self.layoutWidget)
        self.uiChatInputEdit.setObjectName(_fromUtf8("uiChatInputEdit"))
        self.horizontalLayout.addWidget(self.uiChatInputEdit)
        self.uiEmoticonTbtn = QtGui.QToolButton(self.layoutWidget)
        self.uiEmoticonTbtn.setObjectName(_fromUtf8("uiEmoticonTbtn"))
        self.horizontalLayout.addWidget(self.uiEmoticonTbtn)
        self.uiAfkChk = QtGui.QCheckBox(self.layoutWidget)
        self.uiAfkChk.setObjectName(_fromUtf8("uiAfkChk"))
        self.horizontalLayout.addWidget(self.uiAfkChk)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(self.uiSplitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.uiFrmRanked = QtGui.QFrame(self.verticalLayoutWidget)
        self.uiFrmRanked.setMinimumSize(QtCore.QSize(0, 0))
        self.uiFrmRanked.setMaximumSize(QtCore.QSize(16777215, 120))
        self.uiFrmRanked.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiFrmRanked.setFrameShadow(QtGui.QFrame.Raised)
        self.uiFrmRanked.setObjectName(_fromUtf8("uiFrmRanked"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.uiFrmRanked)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.uiBtnRankedOpen = QtGui.QPushButton(self.uiFrmRanked)
        self.uiBtnRankedOpen.setStyleSheet(_fromUtf8("Text-align:left;"))
        self.uiBtnRankedOpen.setFlat(False)
        self.uiBtnRankedOpen.setObjectName(_fromUtf8("uiBtnRankedOpen"))
        self.verticalLayout_11.addWidget(self.uiBtnRankedOpen)
        self.uiSwRanked = QtGui.QStackedWidget(self.uiFrmRanked)
        self.uiSwRanked.setMinimumSize(QtCore.QSize(0, 80))
        self.uiSwRanked.setObjectName(_fromUtf8("uiSwRanked"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.uiRnkLblPing = QtGui.QLabel(self.page_2)
        self.uiRnkLblPing.setObjectName(_fromUtf8("uiRnkLblPing"))
        self.horizontalLayout_9.addWidget(self.uiRnkLblPing)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.uiRnkSliderPing = QtGui.QSlider(self.page_2)
        self.uiRnkSliderPing.setMinimumSize(QtCore.QSize(0, 20))
        self.uiRnkSliderPing.setMaximum(4)
        self.uiRnkSliderPing.setProperty("value", 4)
        self.uiRnkSliderPing.setOrientation(QtCore.Qt.Horizontal)
        self.uiRnkSliderPing.setTickPosition(QtGui.QSlider.TicksAbove)
        self.uiRnkSliderPing.setTickInterval(0)
        self.uiRnkSliderPing.setObjectName(_fromUtf8("uiRnkSliderPing"))
        self.horizontalLayout_3.addWidget(self.uiRnkSliderPing)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem8 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.uiBtnRankedFindMatch = QtGui.QPushButton(self.page_2)
        self.uiBtnRankedFindMatch.setObjectName(_fromUtf8("uiBtnRankedFindMatch"))
        self.horizontalLayout_8.addWidget(self.uiBtnRankedFindMatch)
        spacerItem9 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.uiSwRanked.addWidget(self.page_2)
        self.verticalLayout_11.addWidget(self.uiSwRanked)
        self.verticalLayout_3.addWidget(self.uiFrmRanked)
        self.uiFrmKOTH = QtGui.QFrame(self.verticalLayoutWidget)
        self.uiFrmKOTH.setMinimumSize(QtCore.QSize(0, 0))
        self.uiFrmKOTH.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiFrmKOTH.setFrameShadow(QtGui.QFrame.Raised)
        self.uiFrmKOTH.setObjectName(_fromUtf8("uiFrmKOTH"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.uiFrmKOTH)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.uiBtnKOTHOpen = QtGui.QPushButton(self.uiFrmKOTH)
        self.uiBtnKOTHOpen.setStyleSheet(_fromUtf8("Text-align:left"))
        self.uiBtnKOTHOpen.setObjectName(_fromUtf8("uiBtnKOTHOpen"))
        self.verticalLayout_12.addWidget(self.uiBtnKOTHOpen)
        self.uiFrmKOTH2 = QtGui.QFrame(self.uiFrmKOTH)
        self.uiFrmKOTH2.setMinimumSize(QtCore.QSize(0, 200))
        self.uiFrmKOTH2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.uiFrmKOTH2.setFrameShadow(QtGui.QFrame.Raised)
        self.uiFrmKOTH2.setObjectName(_fromUtf8("uiFrmKOTH2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.uiFrmKOTH2)
        self.verticalLayout_9.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame = QtGui.QFrame(self.uiFrmKOTH2)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.uiLblKOTHKing = QtGui.QLabel(self.frame)
        self.uiLblKOTHKing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uiLblKOTHKing.setObjectName(_fromUtf8("uiLblKOTHKing"))
        self.verticalLayout_7.addWidget(self.uiLblKOTHKing)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.uiLblKOTHStreak = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.uiLblKOTHStreak.setFont(font)
        self.uiLblKOTHStreak.setObjectName(_fromUtf8("uiLblKOTHStreak"))
        self.horizontalLayout_4.addWidget(self.uiLblKOTHStreak)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.uiLblKOTHChallenger = QtGui.QLabel(self.frame)
        self.uiLblKOTHChallenger.setObjectName(_fromUtf8("uiLblKOTHChallenger"))
        self.horizontalLayout_6.addWidget(self.uiLblKOTHChallenger)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_9.addWidget(self.frame)
        self.uiKOTHPlayersTable = QtGui.QTableView(self.uiFrmKOTH2)
        self.uiKOTHPlayersTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.uiKOTHPlayersTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.uiKOTHPlayersTable.setObjectName(_fromUtf8("uiKOTHPlayersTable"))
        self.uiKOTHPlayersTable.horizontalHeader().setStretchLastSection(True)
        self.uiKOTHPlayersTable.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.uiKOTHPlayersTable)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.uiBtnKOTHJoin = QtGui.QPushButton(self.uiFrmKOTH2)
        self.uiBtnKOTHJoin.setObjectName(_fromUtf8("uiBtnKOTHJoin"))
        self.horizontalLayout_21.addWidget(self.uiBtnKOTHJoin)
        self.uiBtnKOTHSpec = QtGui.QPushButton(self.uiFrmKOTH2)
        self.uiBtnKOTHSpec.setObjectName(_fromUtf8("uiBtnKOTHSpec"))
        self.horizontalLayout_21.addWidget(self.uiBtnKOTHSpec)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_12.addWidget(self.uiFrmKOTH2)
        self.verticalLayout_3.addWidget(self.uiFrmKOTH)
        self.uiPlayersTableV = QtGui.QTableView(self.verticalLayoutWidget)
        self.uiPlayersTableV.setObjectName(_fromUtf8("uiPlayersTableV"))
        self.verticalLayout_3.addWidget(self.uiPlayersTableV)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.uiSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAction = QtGui.QMenu(self.menubar)
        self.menuAction.setObjectName(_fromUtf8("menuAction"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.uiThemeMenu = QtGui.QMenu(self.menuSetting)
        self.uiThemeMenu.setObjectName(_fromUtf8("uiThemeMenu"))
        self.uiSmoothingMenu = QtGui.QMenu(self.menuSetting)
        self.uiSmoothingMenu.setObjectName(_fromUtf8("uiSmoothingMenu"))
        self.menuLogging = QtGui.QMenu(self.menuSetting)
        self.menuLogging.setObjectName(_fromUtf8("menuLogging"))
        self.uiChallengeSoundMenu = QtGui.QMenu(self.menuSetting)
        self.uiChallengeSoundMenu.setObjectName(_fromUtf8("uiChallengeSoundMenu"))
        self.uiDesktopCompositionMenu = QtGui.QMenu(self.menuSetting)
        self.uiDesktopCompositionMenu.setObjectName(_fromUtf8("uiDesktopCompositionMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.uiStatusbar = QtGui.QStatusBar(MainWindow)
        self.uiStatusbar.setObjectName(_fromUtf8("uiStatusbar"))
        MainWindow.setStatusBar(self.uiStatusbar)
        self.uiClearChatHistoryAct = QtGui.QAction(MainWindow)
        self.uiClearChatHistoryAct.setObjectName(_fromUtf8("uiClearChatHistoryAct"))
        self.uiAwayAct = QtGui.QAction(MainWindow)
        self.uiAwayAct.setCheckable(True)
        self.uiAwayAct.setObjectName(_fromUtf8("uiAwayAct"))
        self.uiQuitAct = QtGui.QAction(MainWindow)
        self.uiQuitAct.setObjectName(_fromUtf8("uiQuitAct"))
        self.uiMuteChallengeSoundAct = QtGui.QAction(MainWindow)
        self.uiMuteChallengeSoundAct.setCheckable(True)
        self.uiMuteChallengeSoundAct.setObjectName(_fromUtf8("uiMuteChallengeSoundAct"))
        self.uiMuteNotifySoundAct = QtGui.QAction(MainWindow)
        self.uiMuteNotifySoundAct.setCheckable(True)
        self.uiMuteNotifySoundAct.setObjectName(_fromUtf8("uiMuteNotifySoundAct"))
        self.uiFontAct = QtGui.QAction(MainWindow)
        self.uiFontAct.setObjectName(_fromUtf8("uiFontAct"))
        self.uiAboutAct = QtGui.QAction(MainWindow)
        self.uiAboutAct.setObjectName(_fromUtf8("uiAboutAct"))
        self.uiStrevivalAct = QtGui.QAction(MainWindow)
        self.uiStrevivalAct.setObjectName(_fromUtf8("uiStrevivalAct"))
        self.uiHitboxViewerAct = QtGui.QAction(MainWindow)
        self.uiHitboxViewerAct.setObjectName(_fromUtf8("uiHitboxViewerAct"))
        self.uiSafejumpGuideAct = QtGui.QAction(MainWindow)
        self.uiSafejumpGuideAct.setObjectName(_fromUtf8("uiSafejumpGuideAct"))
        self.uiMatchVideosAct = QtGui.QAction(MainWindow)
        self.uiMatchVideosAct.setObjectName(_fromUtf8("uiMatchVideosAct"))
        self.uiSRKForumAct = QtGui.QAction(MainWindow)
        self.uiSRKForumAct.setObjectName(_fromUtf8("uiSRKForumAct"))
        self.uiSRKWikiAct = QtGui.QAction(MainWindow)
        self.uiSRKWikiAct.setObjectName(_fromUtf8("uiSRKWikiAct"))
        self.uiJPWikiAct = QtGui.QAction(MainWindow)
        self.uiJPWikiAct.setObjectName(_fromUtf8("uiJPWikiAct"))
        self.uiGNGThemeAct = QtGui.QAction(MainWindow)
        self.uiGNGThemeAct.setCheckable(True)
        self.uiGNGThemeAct.setObjectName(_fromUtf8("uiGNGThemeAct"))
        self.uiDarkThemeAct = QtGui.QAction(MainWindow)
        self.uiDarkThemeAct.setCheckable(True)
        self.uiDarkThemeAct.setObjectName(_fromUtf8("uiDarkThemeAct"))
        self.uiDebugLogAct = QtGui.QAction(MainWindow)
        self.uiDebugLogAct.setCheckable(True)
        self.uiDebugLogAct.setObjectName(_fromUtf8("uiDebugLogAct"))
        self.uiEmoticonAct = QtGui.QAction(MainWindow)
        self.uiEmoticonAct.setObjectName(_fromUtf8("uiEmoticonAct"))
        self.uiLocateGgpofbaAct = QtGui.QAction(MainWindow)
        self.uiLocateGgpofbaAct.setObjectName(_fromUtf8("uiLocateGgpofbaAct"))
        self.uiLocateROMsAct = QtGui.QAction(MainWindow)
        self.uiLocateROMsAct.setObjectName(_fromUtf8("uiLocateROMsAct"))
        self.uiLocateGeommdbAct = QtGui.QAction(MainWindow)
        self.uiLocateGeommdbAct.setObjectName(_fromUtf8("uiLocateGeommdbAct"))
        self.uiNotifyPlayerStateChangeAct = QtGui.QAction(MainWindow)
        self.uiNotifyPlayerStateChangeAct.setCheckable(True)
        self.uiNotifyPlayerStateChangeAct.setObjectName(_fromUtf8("uiNotifyPlayerStateChangeAct"))
        self.uiFocusOnChatAct = QtGui.QAction(MainWindow)
        self.uiFocusOnChatAct.setObjectName(_fromUtf8("uiFocusOnChatAct"))
        self.uiToggleSidebarAction = QtGui.QAction(MainWindow)
        self.uiToggleSidebarAction.setObjectName(_fromUtf8("uiToggleSidebarAction"))
        self.uiExpandChannelSidebarAct = QtGui.QAction(MainWindow)
        self.uiExpandChannelSidebarAct.setObjectName(_fromUtf8("uiExpandChannelSidebarAct"))
        self.uiContractChannelSidebarAct = QtGui.QAction(MainWindow)
        self.uiContractChannelSidebarAct.setObjectName(_fromUtf8("uiContractChannelSidebarAct"))
        self.uiContractPlayerListAct = QtGui.QAction(MainWindow)
        self.uiContractPlayerListAct.setObjectName(_fromUtf8("uiContractPlayerListAct"))
        self.uiExpandPlayerListAct = QtGui.QAction(MainWindow)
        self.uiExpandPlayerListAct.setObjectName(_fromUtf8("uiExpandPlayerListAct"))
        self.uiLocateUnsupportedSavestatesDirAct = QtGui.QAction(MainWindow)
        self.uiLocateUnsupportedSavestatesDirAct.setObjectName(_fromUtf8("uiLocateUnsupportedSavestatesDirAct"))
        self.uiSyncUnsupportedSavestatesAct = QtGui.QAction(MainWindow)
        self.uiSyncUnsupportedSavestatesAct.setObjectName(_fromUtf8("uiSyncUnsupportedSavestatesAct"))
        self.uiSelectUnsupportedSavestateAct = QtGui.QAction(MainWindow)
        self.uiSelectUnsupportedSavestateAct.setObjectName(_fromUtf8("uiSelectUnsupportedSavestateAct"))
        self.uiFireThemeAct = QtGui.QAction(MainWindow)
        self.uiFireThemeAct.setCheckable(True)
        self.uiFireThemeAct.setObjectName(_fromUtf8("uiFireThemeAct"))
        self.uiCustomQssFileAct = QtGui.QAction(MainWindow)
        self.uiCustomQssFileAct.setCheckable(True)
        self.uiCustomQssFileAct.setObjectName(_fromUtf8("uiCustomQssFileAct"))
        self.uiNormalThemeAct = QtGui.QAction(MainWindow)
        self.uiNormalThemeAct.setCheckable(True)
        self.uiNormalThemeAct.setObjectName(_fromUtf8("uiNormalThemeAct"))
        self.action0 = QtGui.QAction(MainWindow)
        self.action0.setObjectName(_fromUtf8("action0"))
        self.uiCustomEmoticonsAct = QtGui.QAction(MainWindow)
        self.uiCustomEmoticonsAct.setObjectName(_fromUtf8("uiCustomEmoticonsAct"))
        self.uiShowCountryFlagInChatAct = QtGui.QAction(MainWindow)
        self.uiShowCountryFlagInChatAct.setCheckable(True)
        self.uiShowCountryFlagInChatAct.setObjectName(_fromUtf8("uiShowCountryFlagInChatAct"))
        self.uiDisableAutoAnnounceAct = QtGui.QAction(MainWindow)
        self.uiDisableAutoAnnounceAct.setCheckable(True)
        self.uiDisableAutoAnnounceAct.setObjectName(_fromUtf8("uiDisableAutoAnnounceAct"))
        self.uiHideGamesWithoutRomAct = QtGui.QAction(MainWindow)
        self.uiHideGamesWithoutRomAct.setCheckable(True)
        self.uiHideGamesWithoutRomAct.setObjectName(_fromUtf8("uiHideGamesWithoutRomAct"))
        self.uiShowTimestampInChatAct = QtGui.QAction(MainWindow)
        self.uiShowTimestampInChatAct.setCheckable(True)
        self.uiShowTimestampInChatAct.setObjectName(_fromUtf8("uiShowTimestampInChatAct"))
        self.uiDisableAutoColorNicks = QtGui.QAction(MainWindow)
        self.uiDisableAutoColorNicks.setCheckable(True)
        self.uiDisableAutoColorNicks.setObjectName(_fromUtf8("uiDisableAutoColorNicks"))
        self.uiLocateCustomChallengeSoundAct = QtGui.QAction(MainWindow)
        self.uiLocateCustomChallengeSoundAct.setObjectName(_fromUtf8("uiLocateCustomChallengeSoundAct"))
        self.uiLogChatAct = QtGui.QAction(MainWindow)
        self.uiLogChatAct.setCheckable(True)
        self.uiLogChatAct.setObjectName(_fromUtf8("uiLogChatAct"))
        self.uiLogPlayHistoryAct = QtGui.QAction(MainWindow)
        self.uiLogPlayHistoryAct.setCheckable(True)
        self.uiLogPlayHistoryAct.setObjectName(_fromUtf8("uiLogPlayHistoryAct"))
        self.uiGNGWebAct = QtGui.QAction(MainWindow)
        self.uiGNGWebAct.setObjectName(_fromUtf8("uiGNGWebAct"))
        self.uiFilterFavoriteLobbies = QtGui.QAction(MainWindow)
        self.uiFilterFavoriteLobbies.setCheckable(True)
        self.uiFilterFavoriteLobbies.setObjectName(_fromUtf8("uiFilterFavoriteLobbies"))
        self.uiCompositionEnableAct = QtGui.QAction(MainWindow)
        self.uiCompositionEnableAct.setObjectName(_fromUtf8("uiCompositionEnableAct"))
        self.uiCompositionDisableAct = QtGui.QAction(MainWindow)
        self.uiCompositionDisableAct.setObjectName(_fromUtf8("uiCompositionDisableAct"))
        self.actionReport_an_issue = QtGui.QAction(MainWindow)
        self.actionReport_an_issue.setObjectName(_fromUtf8("actionReport_an_issue"))
        self.uiHideInGameChatAct = QtGui.QAction(MainWindow)
        self.uiHideInGameChatAct.setCheckable(True)
        self.uiHideInGameChatAct.setObjectName(_fromUtf8("uiHideInGameChatAct"))
        self.menuAction.addAction(self.uiAwayAct)
        self.menuAction.addAction(self.uiFocusOnChatAct)
        self.menuAction.addAction(self.uiEmoticonAct)
        self.menuAction.addAction(self.uiClearChatHistoryAct)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.uiToggleSidebarAction)
        self.menuAction.addAction(self.uiContractChannelSidebarAct)
        self.menuAction.addAction(self.uiExpandChannelSidebarAct)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.uiContractPlayerListAct)
        self.menuAction.addAction(self.uiExpandPlayerListAct)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.uiQuitAct)
        self.menuLogging.addAction(self.uiLogChatAct)
        self.menuLogging.addAction(self.uiLogPlayHistoryAct)
        self.menuLogging.addSeparator()
        self.menuLogging.addAction(self.uiDebugLogAct)
        self.uiChallengeSoundMenu.addAction(self.uiMuteChallengeSoundAct)
        self.uiChallengeSoundMenu.addAction(self.uiLocateCustomChallengeSoundAct)
        self.uiChallengeSoundMenu.addSeparator()
        self.uiDesktopCompositionMenu.addAction(self.uiCompositionEnableAct)
        self.uiDesktopCompositionMenu.addAction(self.uiCompositionDisableAct)
        self.menuSetting.addAction(self.uiMuteNotifySoundAct)
        self.menuSetting.addAction(self.uiChallengeSoundMenu.menuAction())
        self.menuSetting.addAction(self.uiThemeMenu.menuAction())
        self.menuSetting.addAction(self.uiSmoothingMenu.menuAction())
        self.menuSetting.addAction(self.uiDesktopCompositionMenu.menuAction())
        self.menuSetting.addAction(self.uiFontAct)
        self.menuSetting.addAction(self.uiCustomEmoticonsAct)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.uiLocateROMsAct)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.uiNotifyPlayerStateChangeAct)
        self.menuSetting.addAction(self.uiShowCountryFlagInChatAct)
        self.menuSetting.addAction(self.uiShowTimestampInChatAct)
        self.menuSetting.addAction(self.uiHideInGameChatAct)
        self.menuSetting.addAction(self.uiDisableAutoColorNicks)
        self.menuSetting.addAction(self.uiHideGamesWithoutRomAct)
        self.menuSetting.addAction(self.uiFilterFavoriteLobbies)
        self.menuSetting.addAction(self.menuLogging.menuAction())
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.uiGNGWebAct)
        self.menuAbout.addAction(self.actionReport_an_issue)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.uiAboutAct)
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.uiTmStacked.setCurrentIndex(4)
        self.uiSwRanked.setCurrentIndex(0)
        QtCore.QObject.connect(self.uiQuitAct, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.uiClearChatHistoryAct, QtCore.SIGNAL(_fromUtf8("triggered()")), self.uiChatHistoryTxtB.clear)
        QtCore.QObject.connect(self.uiAwayAct, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.uiAfkChk.setChecked)
        QtCore.QObject.connect(self.uiAfkChk, QtCore.SIGNAL(_fromUtf8("clicked()")), self.uiAwayAct.trigger)
        QtCore.QObject.connect(self.uiFocusOnChatAct, QtCore.SIGNAL(_fromUtf8("triggered()")), self.uiChatInputEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FightCade", None))
        self.uiLblTmTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tournament Title</p></body></html>", None))
        self.uiTmRegStatus.setText(_translate("MainWindow", "Not Registered", None))
        self.uiTmRegTimer.setText(_translate("MainWindow", "Registration ends in 00:00.", None))
        self.uiTmRegisterButton.setText(_translate("MainWindow", "Register", None))
        self.label_3.setText(_translate("MainWindow", "Next Opponent", None))
        self.uiTmNextOpponent.setText(_translate("MainWindow", "Winner of X vs. Y", None))
        self.uiTmLblRound.setText(_translate("MainWindow", "Winners Bracket", None))
        self.uiTmLblMe.setText(_translate("MainWindow", "My name", None))
        self.uiTmLblReadyMe.setText(_translate("MainWindow", "Not ready", None))
        self.uiTmLblOpp.setText(_translate("MainWindow", "Their name", None))
        self.uiTmLblReadyOpp.setText(_translate("MainWindow", "Not ready", None))
        self.uiTmBtnReady.setText(_translate("MainWindow", "Ready", None))
        self.uiTmLblRound2.setText(_translate("MainWindow", "Winners Bracket", None))
        self.label_2.setText(_translate("MainWindow", "Me", None))
        self.uiTmReportMe.setText(_translate("MainWindow", "3", None))
        self.uiTmReportOpp.setText(_translate("MainWindow", "3", None))
        self.label_8.setText(_translate("MainWindow", "Opponent", None))
        self.uiTmBtnSubmit.setText(_translate("MainWindow", "Submit Score", None))
        self.uiTmLblReportStatus.setText(_translate("MainWindow", "asdfasdf", None))
        self.uiTmModP1.setText(_translate("MainWindow", "asdf", None))
        self.uiTmModScore1.setText(_translate("MainWindow", "3", None))
        self.uiTmModScore2.setText(_translate("MainWindow", "3", None))
        self.uiTmModP2.setText(_translate("MainWindow", "asdf", None))
        self.uiTmModScoreSubmit.setText(_translate("MainWindow", "Submit", None))
        self.uiTmModReports.setText(_translate("MainWindow", "Reports: P1 (3-3), P2 (3-3), Automated (3-3)", None))
        self.uiTmBracketLink.setText(_translate("MainWindow", "<center><a href=\"http://www.cnn.com\">Click Here For Bracket</a></center>", None))
        self.uiTmBtnRules.setText(_translate("MainWindow", "Rules", None))
        self.uiTmBtnMod.setText(_translate("MainWindow", "Moderator Tools", None))
        self.uiEmoticonTbtn.setText(_translate("MainWindow", ":)", None))
        self.uiAfkChk.setText(_translate("MainWindow", "away", None))
        self.uiBtnRankedOpen.setText(_translate("MainWindow", "Ranked Match", None))
        self.label_4.setText(_translate("MainWindow", "Connection", None))
        self.uiRnkLblPing.setText(_translate("MainWindow", "Any", None))
        self.uiBtnRankedFindMatch.setText(_translate("MainWindow", "Find Opponent", None))
        self.uiBtnKOTHOpen.setText(_translate("MainWindow", "King Of The Hill", None))
        self.uiLblKOTHKing.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "Streak:", None))
        self.uiLblKOTHStreak.setText(_translate("MainWindow", "10", None))
        self.label_7.setText(_translate("MainWindow", "vs", None))
        self.uiLblKOTHChallenger.setText(_translate("MainWindow", "TextLabel", None))
        self.uiBtnKOTHJoin.setText(_translate("MainWindow", "Join", None))
        self.uiBtnKOTHSpec.setText(_translate("MainWindow", "Spectate", None))
        self.menuAction.setTitle(_translate("MainWindow", "&Action", None))
        self.menuSetting.setTitle(_translate("MainWindow", "S&ettings", None))
        self.uiThemeMenu.setTitle(_translate("MainWindow", "&Theme", None))
        self.uiSmoothingMenu.setTitle(_translate("MainWindow", "Smoothing / Input &lag", None))
        self.menuLogging.setTitle(_translate("MainWindow", "Logging", None))
        self.uiChallengeSoundMenu.setTitle(_translate("MainWindow", "Challenge Sound", None))
        self.uiDesktopCompositionMenu.setTitle(_translate("MainWindow", "Desktop Composition", None))
        self.menuAbout.setTitle(_translate("MainWindow", "&Help", None))
        self.uiClearChatHistoryAct.setText(_translate("MainWindow", "Clear chat his&tory", None))
        self.uiClearChatHistoryAct.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.uiAwayAct.setText(_translate("MainWindow", "Away from k&eyboard", None))
        self.uiAwayAct.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.uiQuitAct.setText(_translate("MainWindow", "&Quit", None))
        self.uiQuitAct.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.uiMuteChallengeSoundAct.setText(_translate("MainWindow", "&Mute Challenge Sound", None))
        self.uiMuteChallengeSoundAct.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.uiMuteNotifySoundAct.setText(_translate("MainWindow", "Mute Notify Sound", None))
        self.uiFontAct.setText(_translate("MainWindow", "&Font", None))
        self.uiAboutAct.setText(_translate("MainWindow", "&About", None))
        self.uiStrevivalAct.setText(_translate("MainWindow", "Strategy && &News", None))
        self.uiHitboxViewerAct.setText(_translate("MainWindow", "Hitbox &Viewer", None))
        self.uiSafejumpGuideAct.setText(_translate("MainWindow", "&Safejump Guide", None))
        self.uiMatchVideosAct.setText(_translate("MainWindow", "&Match Videos", None))
        self.uiSRKForumAct.setText(_translate("MainWindow", "Shoryuken &Forum", None))
        self.uiSRKWikiAct.setText(_translate("MainWindow", "Wiki (English)", None))
        self.uiJPWikiAct.setText(_translate("MainWindow", "Wiki (Japanese)", None))
        self.uiGNGThemeAct.setText(_translate("MainWindow", "&FightCade", None))
        self.uiDarkThemeAct.setText(_translate("MainWindow", "&Dark Orange", None))
        self.uiDebugLogAct.setText(_translate("MainWindow", "Debug &Log", None))
        self.uiEmoticonAct.setText(_translate("MainWindow", "&Insert Emoticon", None))
        self.uiEmoticonAct.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.uiLocateGgpofbaAct.setText(_translate("MainWindow", "&Locate ggpofba-ng.exe", None))
        self.uiLocateROMsAct.setText(_translate("MainWindow", "Locate &ROMs Folder", None))
        self.uiLocateGeommdbAct.setText(_translate("MainWindow", "Locate &GeoIP mmdb", None))
        self.uiNotifyPlayerStateChangeAct.setText(_translate("MainWindow", "&Notify Player State Change", None))
        self.uiFocusOnChatAct.setText(_translate("MainWindow", "Foc&us on chat", None))
        self.uiFocusOnChatAct.setShortcut(_translate("MainWindow", "Ctrl+U", None))
        self.uiToggleSidebarAction.setText(_translate("MainWindow", "To&ggle Channel Sidebar", None))
        self.uiToggleSidebarAction.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.uiExpandChannelSidebarAct.setText(_translate("MainWindow", "&+ Expand Channel Sidebar", None))
        self.uiExpandChannelSidebarAct.setShortcut(_translate("MainWindow", "Ctrl+=", None))
        self.uiContractChannelSidebarAct.setText(_translate("MainWindow", "&- Contract Channel Sidebar", None))
        self.uiContractChannelSidebarAct.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.uiContractPlayerListAct.setText(_translate("MainWindow", "&> Contract Player List", None))
        self.uiContractPlayerListAct.setShortcut(_translate("MainWindow", "Ctrl+.", None))
        self.uiExpandPlayerListAct.setText(_translate("MainWindow", "&< Expand Player List", None))
        self.uiExpandPlayerListAct.setShortcut(_translate("MainWindow", "Ctrl+,", None))
        self.uiLocateUnsupportedSavestatesDirAct.setText(_translate("MainWindow", "Locate &Unsupported Savestates Directory", None))
        self.uiSyncUnsupportedSavestatesAct.setText(_translate("MainWindow", "S&ync Unsupported Savestates", None))
        self.uiSelectUnsupportedSavestateAct.setText(_translate("MainWindow", "&Select Unsupported Savestate", None))
        self.uiSelectUnsupportedSavestateAct.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.uiFireThemeAct.setText(_translate("MainWindow", "&Fire", None))
        self.uiCustomQssFileAct.setText(_translate("MainWindow", "Custom Qss File", None))
        self.uiNormalThemeAct.setText(_translate("MainWindow", "&Normal", None))
        self.action0.setText(_translate("MainWindow", "0", None))
        self.uiCustomEmoticonsAct.setText(_translate("MainWindow", "Custom &Emoticons", None))
        self.uiShowCountryFlagInChatAct.setText(_translate("MainWindow", "Show Country Flag in Chat", None))
        self.uiDisableAutoAnnounceAct.setText(_translate("MainWindow", "&Disable auto announce in unsupported room", None))
        self.uiHideGamesWithoutRomAct.setText(_translate("MainWindow", "Hide Games with Missing ROMs", None))
        self.uiShowTimestampInChatAct.setText(_translate("MainWindow", "Show Timestamp in Chat", None))
        self.uiDisableAutoColorNicks.setText(_translate("MainWindow", "Disable auto-color of Nicknames", None))
        self.uiLocateCustomChallengeSoundAct.setText(_translate("MainWindow", "Custom Challenge Sound", None))
        self.uiLogChatAct.setText(_translate("MainWindow", "Chat history", None))
        self.uiLogPlayHistoryAct.setText(_translate("MainWindow", "Play history", None))
        self.uiGNGWebAct.setText(_translate("MainWindow", "FightCade website", None))
        self.uiFilterFavoriteLobbies.setText(_translate("MainWindow", "Filter Favorite Lobbies", None))
        self.uiCompositionEnableAct.setText(_translate("MainWindow", "Enable", None))
        self.uiCompositionDisableAct.setText(_translate("MainWindow", "Disable (Recommended)", None))
        self.actionReport_an_issue.setText(_translate("MainWindow", "Report an issue", None))
        self.uiHideInGameChatAct.setText(_translate("MainWindow", "Hide in-game Chat on Lobby", None))

from ggpo.gui.completionlineedit import CompletionLineEdit
